# To be used hosting db files in the host pc

services:
  testapp-mysql:
    platform: linux/x86_64
    image: mysql:5.7
    container_name: testapp-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=testapp
      - MYSQL_DATABASE=testapp
      - MYSQL_USER=testapp
      - MYSQL_PASSWORD=testapp
    ports:
      - "3307:3306"
    volumes:
      - "./docker/mysql/db:/var/lib/mysql"
    networks:
      - isolated-nw